name: sepakjudge
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.5.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  path_provider: ^1.6.27
  flutter_share: ^1.0.2+1
  provider: ^4.1.3+1
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: true
  ios: true
  image_path:
    - assets/appIcon.png

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/iconA.png
    - assets/iconB.png
    - assets/balance.png

